per_listener_settings true
listener 8883
protocol mqtt
allow_anonymous false
password_file /mosquitto/secrets/passwords
acl_file /mosquitto/config/acl
cafile /mosquitto/secrets/ca.crt
certfile /mosquitto/secrets/server.crt
keyfile /mosquitto/secrets/server.key
tls_version tlsv1.2
require_certificate false
max_packet_size 32768
message_size_limit 32768
max_queued_messages 256
persistence true
persistence_location /mosquitto/data/
log_type error
log_type warning
connection_messages false
