"""initial read-only management schema"""

import sqlalchemy as sa
from alembic import op

revision = "2f142f5b0a8a"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_events",
        sa.Column("event_id", sa.String(length=36), nullable=False),
        sa.Column("actor", sa.String(length=128), nullable=False),
        sa.Column("action", sa.String(length=64), nullable=False),
        sa.Column("target", sa.String(length=128), nullable=False),
        sa.Column("decision", sa.String(length=64), nullable=False),
        sa.Column("correlation_id", sa.String(length=36), nullable=False),
        sa.Column("timestamp", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("event_id"),
    )
    op.create_table(
        "euiccs",
        sa.Column("eid", sa.String(length=32), nullable=False),
        sa.Column("metadata_json", sa.JSON(), nullable=False),
        sa.Column("updated_at", sa.Float(), nullable=False),
        sa.Column("profiles_observed_at", sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint("eid"),
    )
    op.create_table(
        "idempotency",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("actor", sa.String(length=128), nullable=False),
        sa.Column("key", sa.String(length=128), nullable=False),
        sa.Column("request_hash", sa.String(length=64), nullable=False),
        sa.Column("response", sa.JSON(), nullable=False),
        sa.Column("status_code", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("actor", "key"),
    )
    op.create_table(
        "outbox",
        sa.Column("message_id", sa.String(length=36), nullable=False),
        sa.Column("topic", sa.String(length=256), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("delivered", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("message_id"),
    )
    op.create_table(
        "devices",
        sa.Column("device_id", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("eid", sa.String(length=32), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("state", sa.String(length=32), nullable=False),
        sa.Column("session_id", sa.String(length=36), nullable=True),
        sa.Column("last_seen", sa.Float(), nullable=True),
        sa.Column("created_at", sa.Float(), nullable=False),
        sa.Column("updated_at", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["eid"],
            ["euiccs.eid"],
        ),
        sa.PrimaryKeyConstraint("device_id"),
        sa.UniqueConstraint("eid"),
    )
    op.create_table(
        "operations",
        sa.Column("operation_id", sa.String(length=36), nullable=False),
        sa.Column("eid", sa.String(length=32), nullable=False),
        sa.Column("active_eid", sa.String(length=32), nullable=True),
        sa.Column("operation_type", sa.String(length=32), nullable=False),
        sa.Column("requested_by", sa.String(length=128), nullable=False),
        sa.Column("correlation_id", sa.String(length=36), nullable=False),
        sa.Column("state", sa.String(length=32), nullable=False),
        sa.Column("resource_id", sa.String(length=128), nullable=True),
        sa.Column("request", sa.JSON(), nullable=False),
        sa.Column("raw_outcome", sa.JSON(), nullable=True),
        sa.Column("error", sa.String(length=128), nullable=True),
        sa.Column("created_at", sa.Float(), nullable=False),
        sa.Column("updated_at", sa.Float(), nullable=False),
        sa.Column("next_poll", sa.Float(), nullable=False),
        sa.Column("deadline", sa.Float(), nullable=False),
        sa.Column("lease_token", sa.String(length=36), nullable=True),
        sa.Column("lease_until", sa.Float(), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["eid"],
            ["euiccs.eid"],
        ),
        sa.PrimaryKeyConstraint("operation_id"),
        sa.UniqueConstraint("active_eid"),
        sa.UniqueConstraint("resource_id"),
    )
    op.create_index(op.f("ix_operations_eid"), "operations", ["eid"], unique=False)
    op.create_index(op.f("ix_operations_state"), "operations", ["state"], unique=False)
    op.create_table(
        "profiles",
        sa.Column("eid", sa.String(length=32), nullable=False),
        sa.Column("iccid", sa.String(length=22), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=True),
        sa.Column("provider", sa.String(length=128), nullable=True),
        sa.Column("profile_class", sa.String(length=32), nullable=True),
        sa.Column("state", sa.String(length=32), nullable=True),
        sa.Column("fallback", sa.Boolean(), nullable=True),
        sa.Column("observed_at", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["eid"],
            ["euiccs.eid"],
        ),
        sa.PrimaryKeyConstraint("eid", "iccid"),
    )
    op.create_table(
        "device_commands",
        sa.Column("command_id", sa.String(length=36), nullable=False),
        sa.Column("device_id", sa.String(length=64), nullable=False),
        sa.Column("command_type", sa.String(length=64), nullable=False),
        sa.Column("correlation_id", sa.String(length=36), nullable=False),
        sa.Column("state", sa.String(length=32), nullable=False),
        sa.Column("request", sa.JSON(), nullable=False),
        sa.Column("result", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.Float(), nullable=False),
        sa.Column("expires_at", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["device_id"],
            ["devices.device_id"],
        ),
        sa.PrimaryKeyConstraint("command_id"),
    )
    op.create_index(
        op.f("ix_device_commands_device_id"), "device_commands", ["device_id"], unique=False
    )
    op.create_table(
        "device_observations",
        sa.Column("message_id", sa.String(length=36), nullable=False),
        sa.Column("device_id", sa.String(length=64), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("observed_at", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["device_id"],
            ["devices.device_id"],
        ),
        sa.PrimaryKeyConstraint("message_id"),
    )
    op.create_index(
        op.f("ix_device_observations_device_id"), "device_observations", ["device_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_device_observations_device_id"), table_name="device_observations")
    op.drop_table("device_observations")
    op.drop_index(op.f("ix_device_commands_device_id"), table_name="device_commands")
    op.drop_table("device_commands")
    op.drop_table("profiles")
    op.drop_index(op.f("ix_operations_state"), table_name="operations")
    op.drop_index(op.f("ix_operations_eid"), table_name="operations")
    op.drop_table("operations")
    op.drop_table("devices")
    op.drop_table("outbox")
    op.drop_table("idempotency")
    op.drop_table("euiccs")
    op.drop_table("audit_events")
    # ### end Alembic commands ###
