"""worker readiness heartbeat"""

import sqlalchemy as sa
from alembic import op

revision = "6902ecf52a58"
down_revision = "2f142f5b0a8a"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "service_heartbeats",
        sa.Column("name", sa.String(length=32), nullable=False),
        sa.Column("updated_at", sa.Float(), nullable=False),
        sa.Column("ready", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("name"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("service_heartbeats")
    # ### end Alembic commands ###
